### ISSUE TITLE
Fix "E501" issue in src/client.py

### ISSUE THREAD

**Issue by ArseniyAntonov** [ArseniyAntonov/python-binance-async-client#4]
Line too long (147 > 120 characters)

https://codeclimate.com/github/ArseniyAntonov/python-binance-async-client/src/client.py#issue_5a92404b9e80040001000034

**Comment by Yogendra0Sharma** [comment]
@ArseniyAntonov : I am working on it.

**Comment by ArseniyAntonov** [comment]
@Yogendra0Sharma  thank you for contributing!
